FROM node:0.10-slim
MAINTAINER Hiroki Gota

# Install git, sudo
RUN apt-get -yq update && \
    apt-get -yq install git sudo && \
    apt-get clean && rm -rf /var/lib/apt/lists/*

# Add a user
RUN adduser --disabled-password --gecos '' user && \
	adduser user sudo && \
  	echo "%sudo ALL=(ALL) NOPASSWD:ALL" >> /etc/sudoers
# Set HOME
ENV HOME /home/user

# Install lib dependencies
RUN apt-get -yq update && \
    apt-get -yq install xdg-utils bzip2 libfreetype6 libfontconfig && \
    apt-get clean && rm -rf /var/lib/apt/lists/*

# Install apps
RUN npm install -g grunt-cli@0.1.13 bower@1.7.7 && \
    rm -rf ~/.npm && npm cache clear

#Stop infinite watch
#RUN echo fs.inotify.max_user_watches=524288 | sudo tee -a /etc/sysctl.conf && sudo sysctl -p

# Set app dir
RUN mkdir /app && chown user:user /app
WORKDIR /app

# Run as user
USER user

# Expose the port
EXPOSE 9000 3000 3001

# Open bash by default
CMD /bin/bash
